import jsPDF from "jspdf";

interface CheckInData {
  guestName: string;
  guestEmail: string;
  numberOfGuests: number;
  arrivalDate: string | Date;
  departureDate: string | Date;
  estimatedDepartureHour: string;
  depositConfirmed: boolean;
  conditionConfirmed: boolean;
  signatureDataUrl: string | null;
  createdAt: string | Date;
}

interface CheckOutData {
  guestName: string;
  depositReturned: boolean;
  incidentDescription: string | null;
  createdAt: string | Date;
}

export function exportCheckInPdf(checkIn: CheckInData, propertyName: string): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("SignedStay — Check-In Record", margin, y);
  y += 10;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Property: ${propertyName}`, margin, y);
  y += 7;
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, y);
  y += 10;

  doc.setDrawColor(150);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Guest Information", margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const guestInfo = [
    ["Full Name", checkIn.guestName],
    ["Email Address", checkIn.guestEmail],
    ["Number of Guests", checkIn.numberOfGuests.toString()],
    ["Arrival Date", new Date(checkIn.arrivalDate).toLocaleDateString()],
    ["Departure Date", new Date(checkIn.departureDate).toLocaleDateString()],
    ["Estimated Departure Hour", checkIn.estimatedDepartureHour],
  ];

  guestInfo.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, margin + 55, y);
    y += 6;
  });

  y += 6;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Confirmations", margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Deposit Confirmed:", margin, y);
  doc.text(checkIn.depositConfirmed ? "Yes" : "No", margin + 45, y);
  y += 6;
  doc.text("Villa Condition Confirmed:", margin, y);
  doc.text(checkIn.conditionConfirmed ? "Yes" : "No", margin + 45, y);
  y += 10;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Digital Signature", margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  if (checkIn.signatureDataUrl) {
    try {
      const imgWidth = 80;
      const imgHeight = 30;
      doc.addImage(checkIn.signatureDataUrl, "PNG", margin, y, imgWidth, imgHeight);
      y += imgHeight + 10;
    } catch {
      doc.text("(Unable to load signature image)", margin, y);
      y += 10;
    }
  } else {
    doc.text("No signature provided", margin, y);
    y += 10;
  }

  if (y > 250) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(10);
  doc.setTextColor(128);
  doc.text("Generated by SignedStay · signedstay.com", margin, 285);

  const dateStr = new Date(checkIn.arrivalDate).toISOString().split("T")[0];
  const safeName = checkIn.guestName.replace(/[^a-zA-Z0-9]/g, "-");
  doc.save(`checkin-${safeName}-${dateStr}.pdf`);
}

export function exportCheckOutPdf(checkOut: CheckOutData, propertyName: string): void {
  const doc = new jsPDF();
  const margin = 20;
  let y = 20;

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("SignedStay — Check-Out Record", margin, y);
  y += 10;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Property: ${propertyName}`, margin, y);
  y += 7;
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, y);
  y += 15;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Guest Information", margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Guest Name:", margin, y);
  doc.text(checkOut.guestName, margin + 35, y);
  y += 10;

  doc.text("Deposit Returned:", margin, y);
  doc.text(checkOut.depositReturned ? "Yes" : "No", margin + 35, y);
  y += 10;

  doc.text("Incident Description:", margin, y);
  y += 6;
  const incidentText = checkOut.incidentDescription || "None";
  const splitText = doc.splitTextToSize(incidentText, doc.internal.pageSize.getWidth() - margin * 2);
  doc.text(splitText, margin, y);
  y += splitText.length * 5 + 10;

  doc.setFontSize(10);
  doc.setTextColor(128);
  doc.text("Generated by SignedStay · signedstay.com", margin, 285);

  const dateStr = new Date(checkOut.createdAt).toISOString().split("T")[0];
  const safeName = checkOut.guestName.replace(/[^a-zA-Z0-9]/g, "-");
  doc.save(`checkout-${safeName}-${dateStr}.pdf`);
}